HOST: "127.0.0.1"
PORT: 8000
DEBUG: true
SECRET_KEY: "dev-secret-key-change-in-production"
ALLOWED_HOSTS: "*"

DB_TYPE: "sqlite"
DB_PATH: "development.sqlite"
DB_NAME: "ext_service_dev"
DB_USER: "postgres"
DB_PASSWORD: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_MAX_CONNECTIONS: 10
DB_STALE_TIMEOUT: 300

REDIS_URL: "redis://localhost:6379/0"

JWT_SECRET: "jwt-secret-key-change-in-production"
JWT_ALGORITHM: "HS256"
JWT_EXPIRATION: 3600

LOG_LEVEL: "DEBUG"
LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

RATE_LIMIT_ENABLED: true
RATE_LIMIT_DEFAULT: 100

CACHE_ENABLED: true
CACHE_DEFAULT_TIMEOUT: 300

METRICS_PORT: 8001

API_TITLE: "ext-service API (Development)"
API_VERSION: "1.0.0"
API_DESCRIPTION: "A lightweight routin, flexible web service for building high-performance APIs, microservices and more"

SERVICE_NAME: "ext-service"
RPC_TIMEOUT: 10.0
RPC_MAX_RETRIES: 3
RPC_RETRY_DELAY: 0.5

USER_SERVICE_URL: "http://localhost:8000"
TASK_SERVICE_URL: "http://localhost:8001"