HOST: "0.0.0.0"
PORT: "${PORT:-8000}"
DEBUG: false
SECRET_KEY: "${SECRET_KEY}"
ALLOWED_HOSTS: "${ALLOWED_HOSTS}"

DB_TYPE: "${DB_TYPE:-postgres}"
DB_NAME: "${DB_NAME}"
DB_USER: "${DB_USER}"
DB_PASSWORD: "${DB_PASSWORD}"
DB_HOST: "${DB_HOST}"
DB_PORT: "${DB_PORT}"
DB_MAX_CONNECTIONS: 25
DB_STALE_TIMEOUT: 600

REDIS_URL: "${REDIS_URL}"
REDIS_POOL_SIZE: 10

JWT_SECRET: "${JWT_SECRET}"
JWT_ALGORITHM: "HS256"
JWT_EXPIRATION: 7200

LOG_LEVEL: "${LOG_LEVEL:-INFO}"
LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE: "${LOG_FILE:-/var/log/ext-service.log}"

RATE_LIMIT_ENABLED: true
RATE_LIMIT_DEFAULT: 60

CACHE_ENABLED: true
CACHE_DEFAULT_TIMEOUT: 600

METRICS_PORT: "${METRICS_PORT:-8001}"

SENTRY_DSN: "${SENTRY_DSN}"
SENTRY_ENVIRONMENT: "production"
SENTRY_TRACES_SAMPLE_RATE: 0.1

API_TITLE: "ext-service API (Production)"
API_VERSION: "1.0.0"
API_DESCRIPTION: "A lightweight routin', flexible web service for building high-performance APIs, microservices and more."

SERVICE_NAME: "${SERVICE_NAME:-ext-service}"
RPC_TIMEOUT: "${RPC_TIMEOUT:-10.0}"
RPC_MAX_RETRIES: "${RPC_MAX_RETRIES:-3}"
RPC_RETRY_DELAY: "${RPC_RETRY_DELAY:-0.5}"

USER_SERVICE_URL: "${USER_SERVICE_URL}"
TASK_SERVICE_URL: "${TASK_SERVICE_URL}"